
/**
 * Auth
 */

export const AUTH_DO_LOGIN ="AUTH_DO_LOGIN";
export const AUTH_LOGIN_SUCCESS ="AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILED ="AUTH_LOGIN_FAILED";
export const AUTH_DO_LOGOUT ="AUTH_DO_LOGOUT";
export const AUTH_TRY_COOKIE_AUTH ="AUTH_TRY_COOKIE_AUTH";
export const AUTH_COOKIE_AUTH_FAILED = "AUTH_COOKIE_AUTH_FAILED";
export const AUTH_RECEIVE_USER ="AUTH_RECEIVE_USER";

export const NODES_FETCH ="NODES_FETCH";
export const NODES_RECEIVE ="NODES_RECEIVE";
export const NODES_REQUEST_FAILED ="NODES_REQUEST_FAILED";
export const NODES_SELECT ="NODES_SELECT";

export const MEASUREMENTS_FETCH = "MEASUREMENTS_FETCH";
export const MEASUREMENTS_RECEIVE = "MEASUREMENTS_RECEIVE";
export const MEASUREMENTS_REQUEST_FAILED = "MEASUREMENTS_REQUEST_FAILED";
